package com.example.ui

enum class Language {
    ENGLISH, PERSIAN
}

data class Translation(
    val appTitle: String,
    val login: String,
    val logout: String,
    val username: String,
    val password: String,
    val invalidCredentials: String,
    val adminRole: String,
    val regularUserRole: String,
    val level1Role: String,
    val level2Role: String,
    val selectLanguage: String,
    val loggedInAs: String,
    val role: String,
    val searchPlaceholder: String,
    val fullName: String,
    val jobTitle: String,
    val department: String,
    val shortCode: String,
    val mobileNumber: String,
    val mobileNumberHidden: String,
    val callAction: String,
    val smsAction: String,
    val syncRefreshButton: String,
    val syncingState: String,
    val syncSuccess: String,
    val addContact: String,
    val editContact: String,
    val deleteContact: String,
    val save: String,
    val cancel: String,
    val userAccountsManager: String,
    val createAccount: String,
    val accountList: String,
    val accountCreatedSuccess: String,
    val accountDeletedSuccess: String,
    val deleteAccountConfirm: String,
    val deleteContactConfirm: String,
    val contactSavedSuccess: String,
    val contactDeletedSuccess: String,
    val permissionCallRequired: String,
    val validationRequired: String,
    val adminPanel: String,
    val noContactsFound: String,
    val noUsersFound: String,
    val createAccountHeader: String,
    val aboutApp: String,
    val developerTitle: String,
    val developerName: String,
    val appIntroText: String,
    val editLogs: String,
    val logPerformedBy: String,
    val logItemName: String,
    val logActionType: String,
    val logTime: String,
    val noLogsFound: String,
    val clearLogs: String,
    val logAdd: String,
    val logDelete: String,
    val logUpdate: String,
    val sortBy: String,
    val sortNameAsc: String,
    val sortNameDesc: String,
    val sortDeptAsc: String,
    val sortDeptDesc: String
)

object LocalizedStrings {
    val EN = Translation(
        appTitle = "Organizational phone book of Omran Azarestan Construction Company",
        login = "Login",
        logout = "Log Out",
        username = "Username",
        password = "Password",
        invalidCredentials = "Invalid username or password.",
        adminRole = "Administrator",
        regularUserRole = "Regular User",
        level1Role = "Level 1 (Limited Access)",
        level2Role = "Level 2 (Full Access)",
        selectLanguage = "Language / زبان",
        loggedInAs = "Logged in as",
        role = "Role",
        searchPlaceholder = "Search by name, department, or short code...",
        fullName = "Full Name",
        jobTitle = "Job Title",
        department = "Department",
        shortCode = "Short Code",
        mobileNumber = "Mobile Number",
        mobileNumberHidden = "[Hidden Mobile Number]",
        callAction = "Direct Call",
        smsAction = "Direct SMS",
        syncRefreshButton = "Sync & Refresh",
        syncingState = "Synchronizing list...",
        syncSuccess = "Contacts synchronized successfully!",
        addContact = "Add New Contact",
        editContact = "Edit Contact",
        deleteContact = "Delete Contact",
        save = "Save",
        cancel = "Cancel",
        userAccountsManager = "User Manager",
        createAccount = "Create Account",
        accountList = "Registered Accounts",
        accountCreatedSuccess = "Account created successfully",
        accountDeletedSuccess = "Account deleted successfully",
        deleteAccountConfirm = "Are you sure you want to delete this user account?",
        deleteContactConfirm = "Are you sure you want to delete this contact?",
        contactSavedSuccess = "Contact saved successfully",
        contactDeletedSuccess = "Contact deleted successfully",
        permissionCallRequired = "Placing direct calls requires the CALL_PHONE permission. Opening dialer pad instead.",
        validationRequired = "This field is required",
        adminPanel = "Admin Settings",
        noContactsFound = "No contacts found.",
        noUsersFound = "No user accounts registered.",
        createAccountHeader = "Register New Account",
        aboutApp = "About App",
        developerTitle = "IT & Communications Supervisor",
        developerName = "Mehdi Esmaeili",
        appIntroText = "Organizational Phone Book application for Omran Azarestan Construction Company (Bushehr Project), designed and compiled to handle multi-tier roles, live directory synchronization, department filtering, and direct communication actions.",
        editLogs = "Edit Logs",
        logPerformedBy = "By User",
        logItemName = "Affected Item",
        logActionType = "Action",
        logTime = "Timestamp",
        noLogsFound = "No edit logs recorded yet.",
        clearLogs = "Clear Audit Logs",
        logAdd = "ADDITION",
        logDelete = "DELETION",
        logUpdate = "MODIFICATION",
        sortBy = "Sort By",
        sortNameAsc = "Name (A-Z)",
        sortNameDesc = "Name (Z-A)",
        sortDeptAsc = "Department (A-Z)",
        sortDeptDesc = "Department (Z-A)"
    )

    val FA = Translation(
        appTitle = "دفترچه تلفن سازمانی شرکت عمران آذرستان",
        login = "ورود به سیستم",
        logout = "خروج از حساب",
        username = "نام کاربری",
        password = "رمز عبور",
        invalidCredentials = "نام کاربری یا رمز عبور نامعتبر است.",
        adminRole = "مدیر سیستم (ادمین)",
        regularUserRole = "کاربر عادی",
        level1Role = "کاربر سطح ۱ (دسترسی محدود - بدون موبایل)",
        level2Role = "کاربر سطح ۲ (دسترسی کامل با شماره موبایل)",
        selectLanguage = "زبان / Language",
        loggedInAs = "کاربر فعلی",
        role = "نقش کاربری",
        searchPlaceholder = "جستجو بر اساس نام، واحد، یا کدکوتاه...",
        fullName = "نام و نام خانوادگی",
        jobTitle = "پست سازمانی",
        department = "واحد سازمانی",
        shortCode = "کد کوتاه ۵ رقمی",
        mobileNumber = "شماره موبایل",
        mobileNumberHidden = "[شماره تلفن محفوظ]",
        callAction = "تماس مستقیم",
        smsAction = "ارسال پیامک",
        syncRefreshButton = "همگام‌سازی و بروزرسانی",
        syncingState = "در حال بروزرسانی مخاطبین...",
        syncSuccess = "بایگانی مخاطبین با موفقیت همگام‌سازی شد!",
        addContact = "افزودن مخاطب جدید",
        editContact = "ویرایش مشخصات مخاطب",
        deleteContact = "حذف مخاطب",
        save = "ذخیره تغییرات",
        cancel = "انصراف",
        userAccountsManager = "مدیریت کاربران سازمان",
        createAccount = "ساخت حساب کاربر",
        accountList = "لیست حساب‌های ثبت شده",
        accountCreatedSuccess = "حساب کاربری با موفقیت ایجاد شد",
        accountDeletedSuccess = "حساب کاربری با موفقیت حذف شد",
        deleteAccountConfirm = "آیا از حذف این حساب کاربری مطمئن هستید؟",
        deleteContactConfirm = "آیا از حذف این مخاطب اطمینان دارید؟",
        contactSavedSuccess = "اطلاعات مخاطب با موفقیت ذخیره گردید",
        contactDeletedSuccess = "مخاطب انتخاب شده با موفقیت حذف گردید",
        permissionCallRequired = "برقرار کردن تماس مستقیم نیازمند مجوز سیستمی است. شماره‌گیر سیستم بازگردانده می‌شود.",
        validationRequired = "تکمیل این فیلد الزامی است",
        adminPanel = "تنظیمات ادمین",
        noContactsFound = "هیچ مخاطبی یافت نشد.",
        noUsersFound = "هیچ حساب کاربری یافت نشد.",
        createAccountHeader = "ثبت حساب کاربری جدید",
        aboutApp = "درباره برنامه",
        developerTitle = "سرپرست فناوری اطلاعات و ارتباطات شرکت عمران آذرستان - پروژه بوشهر",
        developerName = "مهدی اسماعیلی",
        appIntroText = "سامانه دفترچه تلفن سازمانی شرکت عمران آذرستان جهت تسریع و تسهیل ارتباطات درون‌سازمانی پروژه بوشهر طراحی گردیده است. این برنامه شامل ویژگی‌های پیشرفته‌ای از جمله کنترل سطح دسترسی هوشمند کاربران بر نمایش شماره همراه، همگام‌سازی لحظه‌ای بایگانی و دسته‌بندی موضوعی بر اساس واحدهای سازمانی می‌باشد.",
        editLogs = "لاگ تغییرات",
        logPerformedBy = "توسط کاربر",
        logItemName = "مورد مربوطه",
        logActionType = "نوع تغییر",
        logTime = "زمان ثبت",
        noLogsFound = "هیچ لاگ تغییراتی تاکنون ثبت نشده است.",
        clearLogs = "پاکسازی تاریخچه لاگ‌ها",
        logAdd = "افزودن جدید",
        logDelete = "حذف رکورد",
        logUpdate = "ویرایش مشخصات",
        sortBy = "مرتب‌سازی بر اساس",
        sortNameAsc = "نام خانوادگی و نام (صعودی)",
        sortNameDesc = "نام خانوادگی و نام (نزولی)",
        sortDeptAsc = "واحد سازمانی (صعودی)",
        sortDeptDesc = "واحد سازمانی (نزولی)"
    )

    fun get(lang: Language): Translation {
        return if (lang == Language.PERSIAN) FA else EN
    }
}
